runtime: go
api_version: go1

handlers:

- url: /.well-known
  static_dir: letsencrypt
  mime_type: text/plain
      
# Load index.html at root.
- url: /$
  static_files: site/index.html
  upload: site/index.html
  secure: always

# Load index.html for each sub directory.
- url: /(.*)/$
  static_files: site/\1/index.html
  upload: site/.*/index.html
  secure: always
 
# Serve everythign else as static files.
- url: /(.+)
  static_files: site/\1
  upload: site/(.*)
  secure: always

# Recommended file skipping declaration from the GAE tutorials
skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - ^\.git/.*
  - \.*\.lint$
  - ^fabfile\.py
  - ^testrunner\.py
  - ^grunt\.js
  - ^node_modules/(.*/)?
